### PR TITLE
converted window.location.replace with window.location.assign

### PR DESCRIPTION
**Pull request by chriswolfdesign**
#### :tophat: What? Why?
Changes all of the instances of window.location.replace to window.location.assign to preserve each page's existence in the user's browser history

#### :pushpin: Related Issues
Fixes https://github.com/mawoka-myblock/ClassQuiz/issues/69 (nice ;-))

#### Testing
I sadly was not able to get your tests running on my machine, though this is a very simple change.  The best way to test this would be to use the application then check that different pages appear in your browser history

#### :clipboard: Checklist
⚠️  No tests suites for now ⚠️
:rotating_light: Please review the [guidelines for contributing](https://github.com/mawoka-myblock/ClassQuiz/blob/master/CONTRIBUTING.md) to this repository.

- [ ] :question: ~~**CONSIDER** adding a unit test if your PR resolves an issue.~~
- [x] :heavy_check_mark: **DO** check open PR's to avoid duplicates.
- [x] :heavy_check_mark: **DO** keep pull requests small so they can be easily reviewed.
- [ ] :heavy_check_mark: **DO** build locally before pushing. could not get to build before or after changes
- [ ] :heavy_check_mark: ~~**DO** make sure tests pass.~~ could not get tests to run before or after changes
- [x] :heavy_check_mark: ~~**DO** add CHANGELOG upgrade notes if required.~~ N/A
- [x] :x:~~**AVOID** breaking the continuous integration build.~~
- [x] :x:**AVOID** making significant changes to the overall architecture.

### :camera: Screenshots
*Please add screenshots of the changes you're proposing*

:hearts: Thank you!

### CODE REVIEW

**Review by mawoka-myblock — APPROVED** [review]
Are you sure, that you've replaced all?

**Comment by mawoka-myblock** [comment]
Thank you soo much! I've never thought, that a stranger comes and contributes to my code! Thank you ❤️ !

**Comment by chriswolfdesign** [comment]
@mawoka-myblock yes, I did a grep to be sure that was every instance window.location.replace

I'm happy to help!  I try to take a little of bit time each week to contribute to lesser known projects.  I hope the rest of the project goes well for you!

**Comment by mawoka-myblock** [comment]
Thank you! I think the difficult part is to find these projects.

**Pull request merged**
