### PR TITLE
:sparkles: add sound to show next

### PR DESCRIPTION
**Pull request by aliaagheisX**
#### :tophat: What? Why?
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #118 `Play audio-file on "Show next question"-button` feaut
- Fixes #?

#### Testing
*Describe the best way to test or validate your PR.*
play and click button `show next`

#### :clipboard: Checklist
⚠️  No tests suites for now ⚠️
:rotating_light: Please review the [guidelines for contributing](https://github.com/mawoka-myblock/ClassQuiz/blob/master/CONTRIBUTING.md) to this repository.

- [x] :question: ~~**CONSIDER** adding a unit test if your PR resolves an issue.~~
- [x] :heavy_check_mark: **DO** check open PR's to avoid duplicates.
- [x] :heavy_check_mark: **DO** keep pull requests small so they can be easily reviewed.
- [x] :heavy_check_mark: **DO** build locally before pushing.
- [x] :heavy_check_mark: ~~**DO** make sure tests pass.~~
- [ ] :heavy_check_mark: ~~**DO** add CHANGELOG upgrade notes if required.~~
- [x] :x:~~**AVOID** breaking the continuous integration build.~~
- [x] :x:**AVOID** making significant changes to the overall architecture.

### :camera: Screenshots
*Please add screenshots of the changes you're proposing*

:hearts: Thank you!

### CODE REVIEW

**Comment by mawoka-myblock** [comment]
I've meant something different, but I still like it! A toggle or switch or something to switch that off would be a really nice addition! What about the copyright of the audio-file? Thank you for your work already!

**Review by mawoka-myblock — CHANGES_REQUESTED** [review]
A switch to switch that off would be cool! If you want, I can also add the switch!

**Comment by mawoka-myblock** [comment]
I'd mark this PR as accepted for the hacktoberfest, if you could tell me about the copyright for the sound. I'll do the rest, if you want.

**Comment by aliaagheisX** [comment]
the licenses of sound: https://creativecommons.org/licenses/by/4.0/
and where I got it: https://freesound.org/people/awrecording.it/sounds/547655/

I'm sorry for not keep working on the rest of the tasks

> I'd mark this PR as accepted for the hacktoberfest, if you could tell me about the copyright for the sound. I'll do the rest, if you want.

**Comment by mawoka-myblock** [comment]
OK, thank you! This PR should appear as completed in your hacktoberfest-dashboard now and rgsnk you for your work!

**Pull request closed without merging**
