### PR TITLE
:bug: Update models.py to make them compatible with current Ormar and Pydantic

### PR DESCRIPTION
**Pull request by BogPlaymate**
Changes are required to work with the current version of ormar (i.e. migrate to ormar 0.20 and above). From the ormar documentation:

"Instead of defining a Meta class now each of the ormar models require an ormar_config parameter that is an instance of the OrmarConfig class. Note that the attribute must be named ormar_config and be an instance of the config class." https://collerek.github.io/ormar/latest/migration/

All the "Meta" nested classes have been removed, and instead the fields implemented in OrmarConfig objects.

Additionally, a Config class, which was previous nested in the User class, has also been removed. The existence of this resulted in a Pydantic error: "pydantic.errors.PydanticUserError: "Config" and "model_config" cannot be used together".

This class only held one value:
class Config:
   use_enum_values = True

As far as I know, the above Config class is not used anywhere. When I searched the project for any references to "use_enum_values", I did not find anything. However, it is possible that I am misunderstanding its use.

Thank you for reading this. These changes are required to build the project with current libraries. Hopefully they will help new developers, and old developers who do a clean install.

#### :tophat: What? Why?
As above 

#### :pushpin: Related Issues
As above

#### Testing
The way to test it is to upgrade the ormar and pydantic libraries on your computer. 

#### :clipboard: Checklist
⚠️  No tests suites for now ⚠️
:rotating_light: Please review the [guidelines for contributing](https://github.com/mawoka-myblock/ClassQuiz/blob/master/CONTRIBUTING.md) to this repository.

- [x] :question: ~~**CONSIDER** adding a unit test if your PR resolves an issue.~~
- [x] :heavy_check_mark: **DO** check open PR's to avoid duplicates.
- [x] :heavy_check_mark: **DO** keep pull requests small so they can be easily reviewed.
- [x] :heavy_check_mark: **DO** build locally before pushing.
- [x] :heavy_check_mark: ~~**DO** make sure tests pass.~~
- [Is it required? Please tell me Answer: No] :heavy_check_mark: ~~**DO** add CHANGELOG upgrade notes if required.~~
- [I am not sure what this means exactly, sorry Answer: No problem] :x:~~**AVOID** breaking the continuous integration build.~~
- [x] :x:**AVOID** making significant changes to the overall architecture.

### :camera: Screenshots
Please let me know if screenshots would be helpful

:hearts: Thank you!

### CODE REVIEW

**Comment by mawoka-myblock** [comment]
Thank you soo much for this PR! I'll take a closer look soon! Regarding the enum config flag:

As far as I remember, this tells/told ormar to map the enum to the custom enum type in the db, so it doesn't store strings or numbers, but I don't know what happened to that in current ormar.

**Comment by BogPlaymate** [comment]
:) Well, thank you so much for the warm reply!

In order to get the project working with current Orman and Pydantic, this
is the models.py that I use. However, maybe I might have made other small
changes to other files. If you do try upgrading Orman/Pydantic, and you get
errors, please tell me! I probably have the solutions on my computer.

Please have a nice day.

**Comment by mawoka-myblock** [comment]
Please also commit all the other changed files, so that'll be easier. It doesn't matter if they are janky, we'll address those together.

**Comment by BogPlaymate** [comment]
That sounds interesting.

I've reviewed the files which I changed. I do believe that the models.py
files is the only file I changed as relates to ormar. Pydantic gave me so
many errors, I can't quite remember if other changes will be necessary to
meet the requirements of the current version.

I did make various other changes. One of them is required to work with the
current version of redis. However, these are probably better addressed in a
separate commit?

**Comment by BogPlaymate** [comment]
To clarify, I mean there may be other changes to work with the current
version of pydantic. I am fairly confident the models.py file will be
enough to make the project compatible with ormar.

**Comment by mawoka-myblock** [comment]
Yea, but please also push the Pipfile and the Pipfile.lock. But when we upgrade pydantic and ormar, all imports will have to be updated to use the V1 and the gradually update from there for all the other pydantic usages throughout ClassQuiz.

**Comment by BogPlaymate** [comment]
I will find out how to push the pipfile and pipfile.lock now.

**Comment by mawoka-myblock** [comment]
`git add Pipfile`, `git add Pipfile.lock`, `git commit -m ":sparkles: Updated Pipfile` & `git push`

**Comment by BogPlaymate** [comment]
Thank you for the command line instructions. I tried using them, and after logging on I get:

"On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Caddyfile
	modified:   classquiz/config.py
	modified:   classquiz/db/models.py
	modified:   classquiz/routers/login.py
	modified:   classquiz/routers/quiz.py
	modified:   classquiz/routers/sitemap.py
	modified:   classquiz/worker/__init__.py
	modified:   docker-compose.yml
	modified:   frontend/Dockerfile
	modified:   frontend/package.json
	modified:   frontend/pnpm-lock.yaml
	modified:   frontend/src/lib/components/commandpalette.svelte
	modified:   frontend/src/routes/+page.svelte
	modified:   frontend/src/routes/account/login/select_method.svelte
	modified:   frontend/src/routes/account/login/start_window.svelte
	modified:   frontend/vite.config.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	classquiz/config (copy).py
	classquiz/db/models (copy).py
	classquiz/routers/sitemap (copy).py
	docker-compose (copy).yml
	frontend/Dockerfile (copy)
	frontend/package (copy).json
	frontend/src/lib/components/BACKUPcommandpalette (copy).svelteBACKUP
	frontend/src/routes/BACKUP+page (copy).svelteBACKUP
	frontend/src/routes/account/login/BACKUPselect_method (copy).svelteBACKUP
	frontend/src/routes/account/login/BACKUPstart_window (copy).svelteBACKUP
	frontend/vite.config (copy).js
	run_tests2.sh
	temptest.sh"

Previously I was using the browser interface, sorry!

**Comment by mawoka-myblock** [comment]
Okay, then for now just run `git add .` and then the commit and push command. This should upload all your changes here. Even though that may not be what you want, there's always time for cleanup which I'll be assisting with tomorrow while you're at sleep ;)

**Comment by BogPlaymate** [comment]
Thank you. You are too kind. I will be home from work in about 11 hours from now. 

I'm having some difficulty authenticating myself via the command line (apparently you cannot do it via password anymore!) Hopefully I will be able to resolve this soon before I leave for work.

**Comment by mawoka-myblock** [comment]
Yes, that's true. You could also try using ssh, but GitHub has some good docs about that, so I'm sure you'll manage that!

**Comment by BogPlaymate** [comment]
:) At least I should be able to log on to github, right?

**Comment by mawoka-myblock** [comment]
The easiest way seems to be to use the github CLI and run the following command: https://cli.github.com/manual/gh_auth_login

**Comment by BogPlaymate** [comment]
Alright, so I'm authenticated on github.

But, the push command gives:

"remote: Permission to mawoka-myblock/ClassQuiz.git denied to BogPlaymate.
fatal: unable to access 'https://github.com/mawoka-myblock/ClassQuiz/': The
requested URL returned error: 403"

Is this because it's pushing to the wrong place (i.e. the main repository)?
Or alternatively it may be because additional authentication is required...

**Comment by BogPlaymate** [comment]
Anyway, thank you for your help late at night. About the time you wake up,
I will get back from work and start trying to reveal my code.

**Comment by mawoka-myblock** [comment]
Yes, exactly. You have to  run "git remote add fork https://github.com/BlogPlaymate/ClassQuiz" and then push with "git push -u fork"

**Comment by BogPlaymate** [comment]
Brilliant, thank you. I looked it up, but actually the commands you suggest
seem much more concise. Right now I'm at my workplace. I will be home in
about two hours and thirty minutes.

**Comment by BogPlaymate** [comment]
Sorry, I had to work late at the school. My apologies.

NOW We have both made a small mistake. And its not clear how to undo it. My
username is "BogPlaymate", however, we spelled it wrong, and now...I can't
seem to add the right fork....

See below. The first command is correct, with "Bog". However, the fork
"Blog" is attached, and this url in fact does not exist.

***@***.***:~/ClassQuiz$ git remote add fork
https://github.com/BogPlaymate/ClassQuiz
error: remote fork already exists.
***@***.***:~/ClassQuiz$ git remote -v
fork https://github.com/BlogPlaymate/ClassQuiz (fetch)
fork https://github.com/BlogPlaymate/ClassQuiz (push)
origin https://github.com/mawoka-myblock/ClassQuiz (fetch)
origin https://github.com/mawoka-myblock/ClassQuiz (push)

**Comment by mawoka-myblock** [comment]
Oh, ofc, it should have been `BogPlaymate`, my bad. You can remove the remote by running `git remote rm fork` and add it back correclty by running `git remote add fork https://github.com/logPlaymate/ClassQuiz.git`

**Comment by BogPlaymate** [comment]
Hi. I've uploaded everything. The commands helped. So, if you want, you can
see the complete picture. It is not linted and doesn't look nice yet
though.

**Comment by mawoka-myblock** [comment]
Just push it. I'll fix the linting errors, etc

**Comment by mawoka-myblock** [comment]
That's what draft PRs are for

**Pull request closed without merging**
