### PR TITLE
Reorder files in main repository folder

### LINKED ISSUE #248: Cleaning up files / ordering in the main folder
**Describe the change and why it is needed**
As a developer, when I want to develop on the ClassQuiz project, I can be confused by the amount of files at the root of the project. While many dotfiles are mandatory for a good project management (CI/CD, documentation etc.), it would be great to do some cleaning of files that do not need to be known from the beginning

**Additional context**
List of small ordering that can be done : 
- [ ] move all `*.sh` files in a dedicated `script` folder
- [ ] create a `docs` folder containing specific documentation files like `SockerIo.md`, `live_redis_data.md`, `logo.png`
- [ ] create a `utils` folder for `*.py` scripts that are useful but do not need to be at

### PR DESCRIPTION
**Pull request by Dynnammo**
#### :tophat: What? Why?
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #248 

#### Testing
*Describe the best way to test or validate your PR.*

#### :clipboard: Checklist
⚠️  No tests suites for now ⚠️
:rotating_light: Please review the [guidelines for contributing](https://github.com/mawoka-myblock/ClassQuiz/blob/master/CONTRIBUTING.md) to this repository.

- [ ] :question: ~~**CONSIDER** adding a unit test if your PR resolves an issue.~~
- [ ] :heavy_check_mark: **DO** check open PR's to avoid duplicates.
- [ ] :heavy_check_mark: **DO** keep pull requests small so they can be easily reviewed.
- [ ] :heavy_check_mark: **DO** build locally before pushing.
- [ ] :heavy_check_mark: ~~**DO** make sure tests pass.~~
- [ ] :heavy_check_mark: ~~**DO** add CHANGELOG upgrade notes if required.~~
- [ ] :x:~~**AVOID** breaking the continuous integration build.~~
- [ ] :x:**AVOID** making significant changes to the overall architecture.

### :camera: Screenshots
*Please add screenshots of the changes you're proposing*

:hearts: Thank you!

### CODE REVIEW

**Review by mawoka-myblock — CHANGES_REQUESTED** [review]
Maybe move the image_cleanup to utils as well?

**Comment by Dynnammo** [comment]
Yes it's done. However I'm wonder how the CI isn't working since I didn't made any change apart from moving files :thinking: . Gonna take a look at it tomorrow

**Comment by mawoka-myblock** [comment]
That's an error on my end, since it's deepsource. the `simulate_players.py` is shit, so I ignored it in deepsource. Since you've moved it, deepsource scans it again and marks the CI as failed.

**Comment by krestenlaust** [comment]
Will this PR still be merged at some point?

**Comment by mawoka-myblock** [comment]
Yes, thought there would be something wrong with it, but there isn't. I'm just gonna have to sort out all the merge conflicts 😭, so it goes back onto my todo's for now, sorry! To be honest, may of these files can also just be removed. Will take a closer look at it when I got the motivation, but thanks for pointing my attention at this PR again, @krestenlaust!

**Comment by krestenlaust** [comment]
> Yes, thought there would be something wrong with it, but there isn't. I'm just gonna have to sort out all the merge conflicts 😭, so it goes back onto my todo's for now, sorry! To be honest, may of these files can also just be removed. Will take a closer look at it when I got the motivation, but thanks for pointing my attention at this PR again, @krestenlaust!

No worries! Don't you think it would be better to just od it over, instead of having to solve merge conflicts related to moving files 🤷  Have a good new year's!

**Comment by Dynnammo** [comment]
> > Yes, thought there would be something wrong with it, but there isn't. I'm just gonna have to sort out all the merge conflicts 😭, so it goes back onto my todo's for now, sorry! To be honest, may of these files can also just be removed. Will take a closer look at it when I got the motivation, but thanks for pointing my attention at this PR again, @krestenlaust!
> 
> No worries! Don't you think it would be better to just od it over, instead of having to solve merge conflicts related to moving files 🤷 Have a good new year's!

Agree to work on it by the end of January if okay for you @mawoka-myblock

**Comment by mawoka-myblock** [comment]
Sure, please go ahead @Dynnammo!

**Pull request closed without merging**
